[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node apps/api/dist/server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10
overlapSeconds = 0
drainingSeconds = 20

[deploy.multiRegionConfig."asia-southeast1-eqsg3a"]
numReplicas = 1
