export const APP_NAME = "KV Infra CRM";

export const API_PREFIX = "/api";

export const SUPPLIER_REQUEST_STATUSES = [
  "SENT",
  "CONFIRMED",
  "RECEIVED",
] as const;

export const DIMENSION_UNIT = "in" as const;
export const VOLUME_UNIT = "m3" as const;
export const CUBIC_INCH_TO_CUBIC_METRE = 0.000016387064;

export const PACKING_MASTER_HEADERS = [
  "SKU",
  "ITEM DESCRIPTION",
  "QUANTITY/CTN",
  "UNIT",
  "WEIGHT/CTN",
  "LENGTH",
  "BREADTH",
  "HEIGHT",
] as const;

export const SUPPLIER_MASTER_HEADERS = [
  "SKU",
  "ITEM DESCRIPTION",
  "NAME",
  "NUMBER",
  "PRIORITY SCALE",
] as const;

export const INVENTORY_HEADERS = [
  "SKU",
  "ITEM DESCRIPTION",
  "QTY / CARTON",
  "UNIT",
  "UNPACKED QTY",
  "IN PACKING QTY",
  "PACKED CTNS",
  "PACKED TOTAL QTY",
  "TOTAL ASSIGNED",
  "AVAILABLE QTY",
  "DEFECTIVE / SHORT QTY",
  "LAST RECEIVED DATE",
  "LAST PACKED DATE",
  "WAREHOUSE LOCATION",
  "NOTES",
  "LAST UPDATED",
] as const;

export const ORDER_HEADERS = [
  "SKU",
  "ITEM DESCRIPTION",
  "QUANTITY/CTN",
  "UNIT",
  "NO OF CTNS",
  "T-QTY",
  "WEIGHT/CTN",
  "GROSS WT",
  "VOLUME",
  "STATUS",
  "LENGTH",
  "BREADTH",
  "HEIGHT",
  "ORDER ID",
  "ORDER LINE ID",
  "ORDER DATE",
  "REQUIRED QTY",
  "RESERVED QTY",
  "SHORTFALL QTY",
  "SUPPLIER REQUEST STATUS",
  "LAST UPDATED",
  "ORDER NOTES",
  "CUSTOMER NAME",
] as const;

export const RECEIVING_LOG_HEADERS = [
  "RECEIPT ID",
  "DATE",
  "SKU",
  "ITEM DESCRIPTION",
  "QTY RECEIVED",
  "UNIT",
  "SUPPLIER",
  "WAREHOUSE LOCATION",
  "RECEIVED BY",
  "NOTES",
  "ITEM CHECK STATUS",
  "ORDER ID",
  "ORDER LINE ID",
] as const;

export const QA_LOG_HEADERS = [
  "PACKING ID",
  "DATE",
  "SKU",
  "ITEM DESCRIPTION",
  "QTY TAKEN FOR PACKING",
  "GOOD QTY",
  "PACKED CTNS",
  "DEFECTIVE QTY",
  "SHORT QTY",
  "ASSIGNED TO ORDER?",
  "ORDER ID",
  "ORDER LINE ID",
  "STATUS",
  "NOTES",
  "LEFT UNPACKED",
] as const;

export const ORDER_ALLOCATION_HEADERS = [
  "ALLOCATION ID",
  "ORDER ID",
  "ORDER LINE ID",
  "SKU",
  "ITEM DESCRIPTION",
  "QTY ASSIGNED",
  "NOTES",
] as const;

export const SUPPLIER_REQUEST_HEADERS = [
  "REQUEST ID",
  "ORDER ID",
  "ORDER LINE ID",
  "SKU",
  "ITEM DESCRIPTION",
  "REQUIRED QTY",
  "AVAILABLE QTY",
  "SHORTFALL QTY",
  "SELECTED SUPPLIER",
  "SUPPLIER NUMBER",
  "SUPPLIER PRIORITY",
  "LAST MESSAGE AT",
  "NEXT FOLLOW-UP AT",
  "STATUS",
  "AUTO FOLLOW-UP ENABLED",
  "NOTES",
] as const;

export const WHATSAPP_LOG_HEADERS = [
  "MESSAGE ID",
  "REQUEST ID",
  "ORDER ID",
  "SKU",
  "SUPPLIER NAME",
  "SUPPLIER NUMBER",
  "MESSAGE TYPE",
  "MESSAGE BODY",
  "SENT AT",
  "ERROR MESSAGE",
  "FOLLOW-UP NUMBER",
  "NOTES",
] as const;
